version: "3.6"
services:
  postgres:
    image: postgres:15-alpine
    ports:
      - "127.0.0.1:7777:5432"
    environment:
      POSTGRES_DB: site
      POSTGRES_PASSWORD: site
      POSTGRES_USER: site

  site:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - postgres
    ports:
      - target: 8000
        published: 8000
    tty: true
    env_file:
      - .env
    environment:
      DATABASE_HOST: postgres
      DATABASE_PORT: 5432
      DATABASE_PASSWORD: site
      DATABASE_NAME: site
      DATABASE_USER: site
      DEBUG: 1
